"""Explicit remote-media acquisition services and contracts."""

from media_catalog.acquisition.planning import (
    AcquisitionPlanPreview,
    AcquisitionSelection,
    PlannedAcquisitionItem,
    check_planned_item_current,
    plan_acquisition,
)
from media_catalog.acquisition.policies import (
    AIBOORU_MEDIA_POLICY,
    DANBOORU_MEDIA_POLICY,
    PIXIV_MEDIA_POLICY,
    CredentialReference,
    DanbooruMediaPolicy,
    MediaRequestPolicy,
    PixivMediaPolicy,
    RequestPolicyError,
    RequestRecipe,
    ResolvedCredentials,
    ResponseExpectations,
    RetryClassification,
    media_request_policy_for_platform,
    safe_failure_diagnostic,
    validate_destination,
    validate_redirect,
)
from media_catalog.acquisition.publication import (
    ClaimComparison,
    PublicationResult,
    compare_declared_claims,
    verify_publish_and_persist,
)
from media_catalog.acquisition.queries import (
    AcquisitionQueryService,
    get_acquisition_plan,
    get_acquisition_run,
    list_acquisition_plans,
    list_acquisition_runs,
    list_retryable_acquisition_items,
)
from media_catalog.acquisition.service import (
    AcquisitionExecutionSummary,
    AcquisitionService,
)
from media_catalog.acquisition.transfer import (
    AttemptTransition,
    HTTPTransferEngine,
    ResumeState,
    TransferBudget,
    TransferLimits,
    TransferResult,
)

__all__ = [
    "AIBOORU_MEDIA_POLICY",
    "DANBOORU_MEDIA_POLICY",
    "PIXIV_MEDIA_POLICY",
    "AcquisitionExecutionSummary",
    "AcquisitionPlanPreview",
    "AcquisitionQueryService",
    "AcquisitionSelection",
    "AcquisitionService",
    "AttemptTransition",
    "ClaimComparison",
    "CredentialReference",
    "DanbooruMediaPolicy",
    "HTTPTransferEngine",
    "MediaRequestPolicy",
    "PixivMediaPolicy",
    "PlannedAcquisitionItem",
    "PublicationResult",
    "RequestPolicyError",
    "RequestRecipe",
    "ResolvedCredentials",
    "ResponseExpectations",
    "ResumeState",
    "RetryClassification",
    "TransferBudget",
    "TransferLimits",
    "TransferResult",
    "check_planned_item_current",
    "compare_declared_claims",
    "get_acquisition_plan",
    "get_acquisition_run",
    "list_acquisition_plans",
    "list_acquisition_runs",
    "list_retryable_acquisition_items",
    "media_request_policy_for_platform",
    "plan_acquisition",
    "safe_failure_diagnostic",
    "validate_destination",
    "validate_redirect",
    "verify_publish_and_persist",
]
