"""Native Gelbooru metadata adapter policy, credentials, and capture utility."""

from media_catalog.adapters.gelbooru.adapter import GelbooruAdapter
from media_catalog.adapters.gelbooru.capture import (
    GelbooruCaptureError,
    GelbooruCaptureOversizedError,
    GelbooruCaptureRedirectError,
    GelbooruCaptureResult,
    GelbooruCaptureTimeoutError,
    capture_gelbooru_dapi_post,
    capture_gelbooru_html_post,
    capture_gelbooru_post,
    validate_post_id,
)
from media_catalog.adapters.gelbooru.config import (
    ADAPTER_VERSION,
    CONTINUATION_VERSION,
    DAPI_SCHEMA_VERSION,
    DAPI_TRANSPORT_VERSION,
    GELBOORU,
    HTML_PARSER_VERSION,
    HTML_SCHEMA_VERSION,
    MAX_PAGE_SIZE,
    MAX_RESPONSE_BYTES,
    MINIMUM_INTERVAL_SECONDS,
    PROVIDER_KEY,
    REQUEST_TIMEOUT_SECONDS,
    GelbooruInstance,
    GelbooruTransport,
)
from media_catalog.adapters.gelbooru.credentials import GelbooruCredentials
from media_catalog.adapters.gelbooru.redaction import (
    REDACTED,
    sanitize_exception,
    sanitize_mapping,
    sanitize_message,
    sanitize_text,
    sanitize_url,
)

__all__ = [
    "ADAPTER_VERSION",
    "CONTINUATION_VERSION",
    "DAPI_SCHEMA_VERSION",
    "DAPI_TRANSPORT_VERSION",
    "GELBOORU",
    "HTML_PARSER_VERSION",
    "HTML_SCHEMA_VERSION",
    "MAX_PAGE_SIZE",
    "MAX_RESPONSE_BYTES",
    "MINIMUM_INTERVAL_SECONDS",
    "PROVIDER_KEY",
    "REDACTED",
    "REQUEST_TIMEOUT_SECONDS",
    "GelbooruAdapter",
    "GelbooruCaptureError",
    "GelbooruCaptureOversizedError",
    "GelbooruCaptureRedirectError",
    "GelbooruCaptureResult",
    "GelbooruCaptureTimeoutError",
    "GelbooruCredentials",
    "GelbooruInstance",
    "GelbooruTransport",
    "capture_gelbooru_dapi_post",
    "capture_gelbooru_html_post",
    "capture_gelbooru_post",
    "sanitize_exception",
    "sanitize_mapping",
    "sanitize_message",
    "sanitize_text",
    "sanitize_url",
    "validate_post_id",
]
