"""Provider-neutral metadata adapter contracts."""

from .contracts import (
    Adapter,
    AdapterFailure,
    AdapterOperation,
    AdapterOutcome,
    AdapterRequest,
    Continuation,
    EnumerationCapabilities,
    EnumerationCapability,
    LookupAdapter,
    LookupCapabilities,
    LookupCapability,
    LookupContinuation,
    LookupPlanConfiguration,
    LookupPlanContext,
    LookupPlanItem,
    LookupQueryMaterial,
    LookupRequest,
    LookupStrategy,
    NormalizedItem,
    NormalizedLookupPage,
    NormalizedLookupResult,
    NormalizedPage,
    ResponseEnvelope,
    TransportIdentityAdapter,
    TransportPair,
    adapter_transport_identity,
    validate_transport_pair,
)
from .fixtures import FixtureCase, FixtureManifest, FixtureSuite, load_fixture_suite

__all__ = [
    "Adapter",
    "AdapterFailure",
    "AdapterOperation",
    "AdapterOutcome",
    "AdapterRequest",
    "Continuation",
    "EnumerationCapabilities",
    "EnumerationCapability",
    "FixtureCase",
    "FixtureManifest",
    "FixtureSuite",
    "LookupAdapter",
    "LookupCapabilities",
    "LookupCapability",
    "LookupContinuation",
    "LookupPlanConfiguration",
    "LookupPlanContext",
    "LookupPlanItem",
    "LookupQueryMaterial",
    "LookupRequest",
    "LookupStrategy",
    "NormalizedItem",
    "NormalizedLookupPage",
    "NormalizedLookupResult",
    "NormalizedPage",
    "ResponseEnvelope",
    "TransportIdentityAdapter",
    "TransportPair",
    "adapter_transport_identity",
    "load_fixture_suite",
    "validate_transport_pair",
]
